workflows:
  ios-release:
    name: iOS Release Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.hggzk.app
      vars:
        BUNDLE_ID: "com.hggzk.app"
        XCODE_WORKSPACE: "hggzk_app/ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          cd hggzk_app
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          cd hggzk_app
          flutter packages pub get
      - name: Install CocoaPods dependencies
        script: |
          cd hggzk_app/ios && pod install
      - name: Flutter build IPA
        script: |
          cd hggzk_app
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - hggzk_app/build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - hggzk_app/flutter_drive.log
    publishing:
      email:
        recipients:
          - ameenmamwn7@gmail.com
        notify:
          success: true
          failure: true

  ios-development:
    name: iOS Development Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      ios_signing:
        distribution_type: development
        bundle_identifier: com.hggzk.app
      vars:
        BUNDLE_ID: "com.hggzk.app"
        XCODE_WORKSPACE: "hggzk_app/ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          cd hggzk_app
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          cd hggzk_app
          flutter packages pub get
      - name: Install CocoaPods dependencies
        script: |
          cd hggzk_app/ios && pod install
      - name: Flutter build IPA (Development)
        script: |
          cd hggzk_app
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - hggzk_app/build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - hggzk_app/flutter_drive.log
    publishing:
      email:
        recipients:
          - ameenmamwn7@gmail.com
        notify:
          success: true
          failure: true
