import 'package:flutter/material.dart';

class IconMapper {
  static IconData getIconFromString(String? iconName) {
    if (iconName == null) return Icons.home_rounded;

    final iconMap = {
      'home': Icons.home_rounded,
      'apartment': Icons.apartment_rounded,
      'villa': Icons.villa_rounded,
      'business': Icons.business_rounded,
      'store': Icons.store_rounded,
      'hotel': Icons.hotel_rounded,
      'house': Icons.house_rounded,
      'cabin': Icons.cabin_rounded,
      'meeting_room': Icons.meeting_room_rounded,
      'stairs': Icons.stairs_rounded,
      'roofing': Icons.roofing_rounded,
      'warehouse': Icons.warehouse_rounded,
      'terrain': Icons.terrain_rounded,
      'grass': Icons.grass_rounded,
      'location_city': Icons.location_city_rounded,
      'cottage': Icons.cottage_rounded,
      'holiday_village': Icons.holiday_village_rounded,
      'gite': Icons.gite_rounded,
      'domain': Icons.domain_rounded,
      'foundation': Icons.foundation_rounded,
      'bed': Icons.bed_rounded,
      'king_bed': Icons.king_bed_rounded,
      'single_bed': Icons.single_bed_rounded,
      'bedroom_parent': Icons.bedroom_parent_rounded,
      'bedroom_child': Icons.bedroom_child_rounded,
      'living_room': Icons.living_rounded,
      'dining_room': Icons.dining_rounded,
      'kitchen': Icons.kitchen_rounded,
      'bathroom': Icons.bathroom_rounded,
      'bathtub': Icons.bathtub_rounded,
      'shower': Icons.shower_rounded,
      'garage': Icons.garage_rounded,
      'balcony': Icons.balcony_rounded,
      'deck': Icons.deck_rounded,
      'yard': Icons.yard_rounded,
      'pool': Icons.pool_rounded,
      'hot_tub': Icons.hot_tub_rounded,
      'fitness_center': Icons.fitness_center_rounded,
      'sports_tennis': Icons.sports_tennis_rounded,
      'sports_soccer': Icons.sports_soccer_rounded,
      'sports_basketball': Icons.sports_basketball_rounded,
      'spa': Icons.spa_rounded,
      'local_parking': Icons.local_parking_rounded,
      'elevator': Icons.elevator_rounded,
      'wifi': Icons.wifi_rounded,
      'ac_unit': Icons.ac_unit_rounded,
      'fireplace': Icons.fireplace_rounded,
      'water_drop': Icons.water_drop_rounded,
      'electric_bolt': Icons.electric_bolt_rounded,
      'cleaning_services': Icons.cleaning_services_rounded,
      'room_service': Icons.room_service_rounded,
      'local_laundry_service': Icons.local_laundry_service_rounded,
      'dry_cleaning': Icons.dry_cleaning_rounded,
      'iron': Icons.iron_rounded,
      'breakfast_dining': Icons.breakfast_dining_rounded,
      'lunch_dining': Icons.lunch_dining_rounded,
      'dinner_dining': Icons.dinner_dining_rounded,
      'restaurant': Icons.restaurant_rounded,
      'local_cafe': Icons.local_cafe_rounded,
      'local_bar': Icons.local_bar_rounded,
      'security': Icons.security_rounded,
      'lock': Icons.lock_rounded,
      'key': Icons.key_rounded,
      'shield': Icons.shield_rounded,
      'verified_user': Icons.verified_user_rounded,
      'safety_check': Icons.safety_check_rounded,
      'emergency': Icons.emergency_rounded,
      'local_police': Icons.local_police_rounded,
      'local_fire_department': Icons.local_fire_department_rounded,
      'medical_services': Icons.medical_services_rounded,
      'location_on': Icons.location_on_rounded,
      'map': Icons.map_rounded,
      'place': Icons.place_rounded,
      'near_me': Icons.near_me_rounded,
      'my_location': Icons.my_location_rounded,
      'directions': Icons.directions_rounded,
      'navigation': Icons.navigation_rounded,
    };

    return iconMap[iconName] ?? Icons.home_rounded;
  }
}
