using System;
using System.Collections.Generic;
using Bogus;
using YemenBooking.Core.Entities;

namespace YemenBooking.Core.Seeds
{
    /// <summary>
    /// مولد البيانات الأولية لكائن User
    /// </summary>
    public class UserSeeder : ISeeder<User>
    {
        public IEnumerable<User> SeedData()
        {
            // Fixed: Use static date instead of DateTime.UtcNow for PostgreSQL compatibility
            var seedDate = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc);
            // تاريخ التحقق من البريد - مهم جداً لتطبيق الموبايل
            var emailVerifiedDate = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc);
            
            return new List<User>
            {
                new User
                {
                    Id = Guid.Parse("AAAAAAAA-AAAA-AAAA-AAAA-AAAAAAAAAAAA"),
                    Name = "Admin User",
                    Email = "admin@example.com",
                    Password = "Admin@123",
                    Phone = "1234567890",
                    ProfileImage = "",
                    CreatedAt = seedDate,
                    IsActive = true,
                    LastLoginDate = seedDate,
                    TotalSpent = 0m,
                    LoyaltyTier = "Gold",
                    EmailConfirmed = true,
                    IsEmailVerified = true,
                    EmailVerifiedAt = emailVerifiedDate, // ⭐ مهم: هذا الحقل يحدد حالة التحقق في الموبايل
                    EmailConfirmationToken = null,
                    EmailConfirmationTokenExpires = null,
                    PasswordResetToken = null,
                    PasswordResetTokenExpires = null,
                    SettingsJson = "{}",
                    FavoritesJson = "[]",
                    TimeZoneId = "Asia/Aden",
                    Country = "Yemen",
                    City = "Sana'a"
                },
                // ملاك متعددون (كل مالك له عقار واحد)
                new User
                {
                    Id = Guid.Parse("BBBBBBBB-BBBB-BBBB-BBBB-BBBBBBBBBB01"),
                    Name = "Property Owner 01",
                    Email = "owner01@example.com",
                    Password = "Owner@123",
                    Phone = "770000001",
                    ProfileImage = "",
                    CreatedAt = seedDate,
                    IsActive = true,
                    LastLoginDate = seedDate,
                    TotalSpent = 0m,
                    LoyaltyTier = "Silver",
                    EmailConfirmed = true,
                    IsEmailVerified = true,
                    EmailVerifiedAt = emailVerifiedDate,
                    EmailConfirmationToken = null,
                    EmailConfirmationTokenExpires = null,
                    PasswordResetToken = null,
                    PasswordResetTokenExpires = null,
                    SettingsJson = "{}",
                    FavoritesJson = "[]",
                    TimeZoneId = "Asia/Aden",
                    Country = "Yemen",
                    City = "Aden"
                },
                new User
                {
                    Id = Guid.Parse("BBBBBBBB-BBBB-BBBB-BBBB-BBBBBBBBBB02"),
                    Name = "Property Owner 02",
                    Email = "owner02@example.com",
                    Password = "Owner@123",
                    Phone = "770000002",
                    ProfileImage = "",
                    CreatedAt = seedDate,
                    IsActive = true,
                    LastLoginDate = seedDate,
                    TotalSpent = 0m,
                    LoyaltyTier = "Silver",
                    EmailConfirmed = true,
                    IsEmailVerified = true,
                    EmailVerifiedAt = emailVerifiedDate,
                    EmailConfirmationToken = null,
                    EmailConfirmationTokenExpires = null,
                    PasswordResetToken = null,
                    PasswordResetTokenExpires = null,
                    SettingsJson = "{}",
                    FavoritesJson = "[]",
                    TimeZoneId = "Asia/Aden",
                    Country = "Yemen",
                    City = "Aden"
                },
                new User
                {
                    Id = Guid.Parse("BBBBBBBB-BBBB-BBBB-BBBB-BBBBBBBBBB03"),
                    Name = "Property Owner 03",
                    Email = "owner03@example.com",
                    Password = "Owner@123",
                    Phone = "770000003",
                    ProfileImage = "",
                    CreatedAt = seedDate,
                    IsActive = true,
                    LastLoginDate = seedDate,
                    TotalSpent = 0m,
                    LoyaltyTier = "Silver",
                    EmailConfirmed = true,
                    IsEmailVerified = true,
                    EmailVerifiedAt = emailVerifiedDate,
                    EmailConfirmationToken = null,
                    EmailConfirmationTokenExpires = null,
                    PasswordResetToken = null,
                    PasswordResetTokenExpires = null,
                    SettingsJson = "{}",
                    FavoritesJson = "[]",
                    TimeZoneId = "Asia/Aden",
                    Country = "Yemen",
                    City = "Aden"
                },
                new User
                {
                    Id = Guid.Parse("BBBBBBBB-BBBB-BBBB-BBBB-BBBBBBBBBB04"),
                    Name = "Property Owner 04",
                    Email = "owner04@example.com",
                    Password = "Owner@123",
                    Phone = "770000004",
                    ProfileImage = "",
                    CreatedAt = seedDate,
                    IsActive = true,
                    LastLoginDate = seedDate,
                    TotalSpent = 0m,
                    LoyaltyTier = "Silver",
                    EmailConfirmed = true,
                    IsEmailVerified = true,
                    EmailVerifiedAt = emailVerifiedDate,
                    EmailConfirmationToken = null,
                    EmailConfirmationTokenExpires = null,
                    PasswordResetToken = null,
                    PasswordResetTokenExpires = null,
                    SettingsJson = "{}",
                    FavoritesJson = "[]",
                    TimeZoneId = "Asia/Aden",
                    Country = "Yemen",
                    City = "Aden"
                },
                new User
                {
                    Id = Guid.Parse("BBBBBBBB-BBBB-BBBB-BBBB-BBBBBBBBBB05"),
                    Name = "Property Owner 05",
                    Email = "owner05@example.com",
                    Password = "Owner@123",
                    Phone = "770000005",
                    ProfileImage = "",
                    CreatedAt = seedDate,
                    IsActive = true,
                    LastLoginDate = seedDate,
                    TotalSpent = 0m,
                    LoyaltyTier = "Silver",
                    EmailConfirmed = true,
                    IsEmailVerified = true,
                    EmailVerifiedAt = emailVerifiedDate,
                    EmailConfirmationToken = null,
                    EmailConfirmationTokenExpires = null,
                    PasswordResetToken = null,
                    PasswordResetTokenExpires = null,
                    SettingsJson = "{}",
                    FavoritesJson = "[]",
                    TimeZoneId = "Asia/Aden",
                    Country = "Yemen",
                    City = "Aden"
                },
                new User
                {
                    Id = Guid.Parse("BBBBBBBB-BBBB-BBBB-BBBB-BBBBBBBBBB06"),
                    Name = "Property Owner 06",
                    Email = "owner06@example.com",
                    Password = "Owner@123",
                    Phone = "770000006",
                    ProfileImage = "",
                    CreatedAt = seedDate,
                    IsActive = true,
                    LastLoginDate = seedDate,
                    TotalSpent = 0m,
                    LoyaltyTier = "Silver",
                    EmailConfirmed = true,
                    IsEmailVerified = true,
                    EmailVerifiedAt = emailVerifiedDate,
                    EmailConfirmationToken = null,
                    EmailConfirmationTokenExpires = null,
                    PasswordResetToken = null,
                    PasswordResetTokenExpires = null,
                    SettingsJson = "{}",
                    FavoritesJson = "[]",
                    TimeZoneId = "Asia/Aden",
                    Country = "Yemen",
                    City = "Aden"
                },
                new User
                {
                    Id = Guid.Parse("BBBBBBBB-BBBB-BBBB-BBBB-BBBBBBBBBB07"),
                    Name = "Property Owner 07",
                    Email = "owner07@example.com",
                    Password = "Owner@123",
                    Phone = "770000007",
                    ProfileImage = "",
                    CreatedAt = seedDate,
                    IsActive = true,
                    LastLoginDate = seedDate,
                    TotalSpent = 0m,
                    LoyaltyTier = "Silver",
                    EmailConfirmed = true,
                    IsEmailVerified = true,
                    EmailVerifiedAt = emailVerifiedDate,
                    EmailConfirmationToken = null,
                    EmailConfirmationTokenExpires = null,
                    PasswordResetToken = null,
                    PasswordResetTokenExpires = null,
                    SettingsJson = "{}",
                    FavoritesJson = "[]",
                    TimeZoneId = "Asia/Aden",
                    Country = "Yemen",
                    City = "Aden"
                },
                new User
                {
                    Id = Guid.Parse("BBBBBBBB-BBBB-BBBB-BBBB-BBBBBBBBBB08"),
                    Name = "Property Owner 08",
                    Email = "owner08@example.com",
                    Password = "Owner@123",
                    Phone = "770000008",
                    ProfileImage = "",
                    CreatedAt = seedDate,
                    IsActive = true,
                    LastLoginDate = seedDate,
                    TotalSpent = 0m,
                    LoyaltyTier = "Silver",
                    EmailConfirmed = true,
                    IsEmailVerified = true,
                    EmailVerifiedAt = emailVerifiedDate,
                    EmailConfirmationToken = null,
                    EmailConfirmationTokenExpires = null,
                    PasswordResetToken = null,
                    PasswordResetTokenExpires = null,
                    SettingsJson = "{}",
                    FavoritesJson = "[]",
                    TimeZoneId = "Asia/Aden",
                    Country = "Yemen",
                    City = "Aden"
                },
                new User
                {
                    Id = Guid.Parse("BBBBBBBB-BBBB-BBBB-BBBB-BBBBBBBBBB09"),
                    Name = "Property Owner 09",
                    Email = "owner09@example.com",
                    Password = "Owner@123",
                    Phone = "770000009",
                    ProfileImage = "",
                    CreatedAt = seedDate,
                    IsActive = true,
                    LastLoginDate = seedDate,
                    TotalSpent = 0m,
                    LoyaltyTier = "Silver",
                    EmailConfirmed = true,
                    IsEmailVerified = true,
                    EmailVerifiedAt = emailVerifiedDate,
                    EmailConfirmationToken = null,
                    EmailConfirmationTokenExpires = null,
                    PasswordResetToken = null,
                    PasswordResetTokenExpires = null,
                    SettingsJson = "{}",
                    FavoritesJson = "[]",
                    TimeZoneId = "Asia/Aden",
                    Country = "Yemen",
                    City = "Aden"
                },
                new User
                {
                    Id = Guid.Parse("BBBBBBBB-BBBB-BBBB-BBBB-BBBBBBBBBB10"),
                    Name = "Property Owner 10",
                    Email = "owner10@example.com",
                    Password = "Owner@123",
                    Phone = "770000010",
                    ProfileImage = "",
                    CreatedAt = seedDate,
                    IsActive = true,
                    LastLoginDate = seedDate,
                    TotalSpent = 0m,
                    LoyaltyTier = "Silver",
                    EmailConfirmed = true,
                    IsEmailVerified = true,
                    EmailVerifiedAt = emailVerifiedDate,
                    EmailConfirmationToken = null,
                    EmailConfirmationTokenExpires = null,
                    PasswordResetToken = null,
                    PasswordResetTokenExpires = null,
                    SettingsJson = "{}",
                    FavoritesJson = "[]",
                    TimeZoneId = "Asia/Aden",
                    Country = "Yemen",
                    City = "Aden"
                },
                new User
                {
                    Id = Guid.Parse("BBBBBBBB-BBBB-BBBB-BBBB-BBBBBBBBBB11"),
                    Name = "Property Owner 11",
                    Email = "owner11@example.com",
                    Password = "Owner@123",
                    Phone = "770000011",
                    ProfileImage = "",
                    CreatedAt = seedDate,
                    IsActive = true,
                    LastLoginDate = seedDate,
                    TotalSpent = 0m,
                    LoyaltyTier = "Silver",
                    EmailConfirmed = true,
                    IsEmailVerified = true,
                    EmailVerifiedAt = emailVerifiedDate,
                    EmailConfirmationToken = null,
                    EmailConfirmationTokenExpires = null,
                    PasswordResetToken = null,
                    PasswordResetTokenExpires = null,
                    SettingsJson = "{}",
                    FavoritesJson = "[]",
                    TimeZoneId = "Asia/Aden",
                    Country = "Yemen",
                    City = "Aden"
                },
                new User
                {
                    Id = Guid.Parse("BBBBBBBB-BBBB-BBBB-BBBB-BBBBBBBBBB12"),
                    Name = "Property Owner 12",
                    Email = "owner12@example.com",
                    Password = "Owner@123",
                    Phone = "770000012",
                    ProfileImage = "",
                    CreatedAt = seedDate,
                    IsActive = true,
                    LastLoginDate = seedDate,
                    TotalSpent = 0m,
                    LoyaltyTier = "Silver",
                    EmailConfirmed = true,
                    IsEmailVerified = true,
                    EmailVerifiedAt = emailVerifiedDate,
                    EmailConfirmationToken = null,
                    EmailConfirmationTokenExpires = null,
                    PasswordResetToken = null,
                    PasswordResetTokenExpires = null,
                    SettingsJson = "{}",
                    FavoritesJson = "[]",
                    TimeZoneId = "Asia/Aden",
                    Country = "Yemen",
                    City = "Aden"
                },
                new User
                {
                    Id = Guid.Parse("BBBBBBBB-BBBB-BBBB-BBBB-BBBBBBBBBB13"),
                    Name = "Property Owner 13",
                    Email = "owner13@example.com",
                    Password = "Owner@123",
                    Phone = "770000013",
                    ProfileImage = "",
                    CreatedAt = seedDate,
                    IsActive = true,
                    LastLoginDate = seedDate,
                    TotalSpent = 0m,
                    LoyaltyTier = "Silver",
                    EmailConfirmed = true,
                    IsEmailVerified = true,
                    EmailVerifiedAt = emailVerifiedDate,
                    EmailConfirmationToken = null,
                    EmailConfirmationTokenExpires = null,
                    PasswordResetToken = null,
                    PasswordResetTokenExpires = null,
                    SettingsJson = "{}",
                    FavoritesJson = "[]",
                    TimeZoneId = "Asia/Aden",
                    Country = "Yemen",
                    City = "Aden"
                },
                new User
                {
                    Id = Guid.Parse("BBBBBBBB-BBBB-BBBB-BBBB-BBBBBBBBBB14"),
                    Name = "Property Owner 14",
                    Email = "owner14@example.com",
                    Password = "Owner@123",
                    Phone = "770000014",
                    ProfileImage = "",
                    CreatedAt = seedDate,
                    IsActive = true,
                    LastLoginDate = seedDate,
                    TotalSpent = 0m,
                    LoyaltyTier = "Silver",
                    EmailConfirmed = true,
                    IsEmailVerified = true,
                    EmailVerifiedAt = emailVerifiedDate,
                    EmailConfirmationToken = null,
                    EmailConfirmationTokenExpires = null,
                    PasswordResetToken = null,
                    PasswordResetTokenExpires = null,
                    SettingsJson = "{}",
                    FavoritesJson = "[]",
                    TimeZoneId = "Asia/Aden",
                    Country = "Yemen",
                    City = "Aden"
                },
                new User
                {
                    Id = Guid.Parse("BBBBBBBB-BBBB-BBBB-BBBB-BBBBBBBBBB15"),
                    Name = "Property Owner 15",
                    Email = "owner15@example.com",
                    Password = "Owner@123",
                    Phone = "770000015",
                    ProfileImage = "",
                    CreatedAt = seedDate,
                    IsActive = true,
                    LastLoginDate = seedDate,
                    TotalSpent = 0m,
                    LoyaltyTier = "Silver",
                    EmailConfirmed = true,
                    IsEmailVerified = true,
                    EmailVerifiedAt = emailVerifiedDate,
                    EmailConfirmationToken = null,
                    EmailConfirmationTokenExpires = null,
                    PasswordResetToken = null,
                    PasswordResetTokenExpires = null,
                    SettingsJson = "{}",
                    FavoritesJson = "[]",
                    TimeZoneId = "Asia/Aden",
                    Country = "Yemen",
                    City = "Aden"
                },
                // مستخدمون إضافيون للحجوزات
                new User
                {
                    Id = Guid.Parse("C0000000-0000-0000-0000-000000000001"),
                    Name = "أحمد محمد علي",
                    Email = "ahmed.mohamed@example.com",
                    Password = "User@123",
                    Phone = "777111222",
                    ProfileImage = "",
                    CreatedAt = seedDate,
                    IsActive = true,
                    LastLoginDate = seedDate.AddDays(-5),
                    TotalSpent = 0m,
                    LoyaltyTier = "Bronze",
                    EmailConfirmed = true,
                    IsEmailVerified = true,
                    EmailVerifiedAt = emailVerifiedDate,
                    EmailConfirmationToken = null,
                    EmailConfirmationTokenExpires = null,
                    PasswordResetToken = null,
                    PasswordResetTokenExpires = null,
                    SettingsJson = "{}",
                    FavoritesJson = "[]",
                    TimeZoneId = "Asia/Aden",
                    Country = "Yemen",
                    City = "صنعاء"
                },
                new User
                {
                    Id = Guid.Parse("C0000000-0000-0000-0000-000000000002"),
                    Name = "فاطمة حسن عبدالله",
                    Email = "fatima.hassan@example.com",
                    Password = "User@123",
                    Phone = "777222333",
                    ProfileImage = "",
                    CreatedAt = seedDate,
                    IsActive = true,
                    LastLoginDate = seedDate.AddDays(-3),
                    TotalSpent = 0m,
                    LoyaltyTier = "Silver",
                    EmailConfirmed = true,
                    IsEmailVerified = true,
                    EmailVerifiedAt = emailVerifiedDate,
                    EmailConfirmationToken = null,
                    EmailConfirmationTokenExpires = null,
                    PasswordResetToken = null,
                    PasswordResetTokenExpires = null,
                    SettingsJson = "{}",
                    FavoritesJson = "[]",
                    TimeZoneId = "Asia/Aden",
                    Country = "Yemen",
                    City = "عدن"
                },
                new User
                {
                    Id = Guid.Parse("C0000000-0000-0000-0000-000000000003"),
                    Name = "خالد صالح قاسم",
                    Email = "khaled.saleh@example.com",
                    Password = "User@123",
                    Phone = "777333444",
                    ProfileImage = "",
                    CreatedAt = seedDate,
                    IsActive = true,
                    LastLoginDate = seedDate.AddDays(-2),
                    TotalSpent = 0m,
                    LoyaltyTier = "Gold",
                    EmailConfirmed = true,
                    IsEmailVerified = true,
                    EmailVerifiedAt = emailVerifiedDate,
                    EmailConfirmationToken = null,
                    EmailConfirmationTokenExpires = null,
                    PasswordResetToken = null,
                    PasswordResetTokenExpires = null,
                    SettingsJson = "{}",
                    FavoritesJson = "[]",
                    TimeZoneId = "Asia/Aden",
                    Country = "Yemen",
                    City = "تعز"
                },
                new User
                {
                    Id = Guid.Parse("C0000000-0000-0000-0000-000000000004"),
                    Name = "مريم عبدالرحمن سعيد",
                    Email = "mariam.said@example.com",
                    Password = "User@123",
                    Phone = "777444555",
                    ProfileImage = "",
                    CreatedAt = seedDate,
                    IsActive = true,
                    LastLoginDate = seedDate.AddDays(-1),
                    TotalSpent = 0m,
                    LoyaltyTier = "Bronze",
                    EmailConfirmed = true,
                    IsEmailVerified = true,
                    EmailVerifiedAt = emailVerifiedDate,
                    EmailConfirmationToken = null,
                    EmailConfirmationTokenExpires = null,
                    PasswordResetToken = null,
                    PasswordResetTokenExpires = null,
                    SettingsJson = "{}",
                    FavoritesJson = "[]",
                    TimeZoneId = "Asia/Aden",
                    Country = "Yemen",
                    City = "صنعاء"
                },
                new User
                {
                    Id = Guid.Parse("C0000000-0000-0000-0000-000000000005"),
                    Name = "ياسر عبدالله محمد",
                    Email = "yasser.abdullah@example.com",
                    Password = "User@123",
                    Phone = "777555666",
                    ProfileImage = "",
                    CreatedAt = seedDate,
                    IsActive = true,
                    LastLoginDate = seedDate,
                    TotalSpent = 0m,
                    LoyaltyTier = "Silver",
                    EmailConfirmed = true,
                    IsEmailVerified = true,
                    EmailVerifiedAt = emailVerifiedDate,
                    EmailConfirmationToken = null,
                    EmailConfirmationTokenExpires = null,
                    PasswordResetToken = null,
                    PasswordResetTokenExpires = null,
                    SettingsJson = "{}",
                    FavoritesJson = "[]",
                    TimeZoneId = "Asia/Aden",
                    Country = "Yemen",
                    City = "عدن"
                }
            };
        }
    }
} 